### ISSUE TITLE
Are there any docs?

### ISSUE THREAD

**Issue by utabe** [smurfix/trio-aiohttp#4]
I couldn't find any documentation. Are there any docs for this project?

**Comment by smurfix** [comment]
No. This project is inactive. For a Trio-compatible http client check "asks", for a reasonable server framework "quart".

**Comment by utabe** [comment]
Sounds good. Thank you for the suggestions.

**Comment by scopatz** [comment]
Thanks for the suggestion @smurfix - Does quart work with trio out of the box, or is there something special that you need to do.  The quart docs don't seem to mention trio at all

**Comment by smurfix** [comment]
There's a separate `quart_trio` extension module (by the same author).

**Comment by scopatz** [comment]
Found it, thanks!
